name: CI Ecosoft

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # ------- FRONTEND -------
      - name: Instalar dependencias frontend
        run: |
          cd frontend
          npm install

      - name: Compilar frontend
        run: |
          cd frontend
          npm run build

      - name: Linter frontend
        run: |
          cd frontend
          npm run lint || echo "No hay lint configurado"

      - name: Tests frontend
        run: |
          cd frontend
          npm test || echo "No hay tests configurados"

      # ------- BACKEND -------
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias backend
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Tests backend
        run: |
          cd backend
          pytest || echo "No hay tests configurados"
