name: CI Ecosoft

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (frontend)
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Run tests (frontend)
        run: npm test

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (backend)
        run: |
          if [ -f manage.py ]; then python manage.py test; fi
          if [ -d tests ]; then pytest; fi

